[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qnpack"
version = "1.2.0"
description = "Quantum Network Repeater Simulation Package"
readme = "README.md"
license = "BSD-3-Clause-LBNL"
license-files = ["LICENSE", "COPYRIGHT"]
requires-python = ">=3.12,<3.13"
authors = [
    { name = "Charu Jain" },
    { name = "Chuen Hei Chan" },
    { name = "Se-young Yu" },
    { name = "Ezra Kissel" },
    { name = "Wenji Wu" },
]
maintainers = [
    { name = "qnpack", email = "qnpack@es.net" },
]
keywords = ["quantum", "network", "repeater", "photonic", "simulation"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "munch==4.0.0",
    "pyyaml",
    "networkx",
    "matplotlib",
    "netsquid==1.1.8",
    "netsquid-trappedions==4.0.0",
    "pytket",
    "openqasm3[parser]"
]

[project.urls]
Homepage = "https://github.com/quant-net/repeater-simulations"

[project.scripts]
qnpack = "qnpack.qnpack:main"
dqc-sim = "qnpack.dqc.sim:main"

[tool.setuptools.packages.find]
include = ["qnpack", "qnpack.*"]

[[tool.uv.index]]
name = "netsquid"
url = "https://pypi.netsquid.org/"

[tool.uv.sources]
netsquid = { index = "netsquid" }
netsquid-trappedions = { index = "netsquid" }
